title: IT Artist
subtitle: IT 기술을 예술의 경지로!
description: >- # this means to ignore newlines until "baseurl:"
  시스템, 네트워크, 보안, 개발, 데이터베이스, 보안장비, 가상화, 클라우드, wargame, 신나게 즐기자
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
disqus_shortname: sujay-kundu  #for comments using disqus
author: devlopr
author_bio: 대전에 살고있으며, 부족한 능력때문에 고군분투 하는중..!!
author_email: "hunter0x01@gmail.com"
author_location: Korea
author_website_url: "https://hunter0x01.github.io"

# social links
twitter_username: hunter0x01
github_username:  hunter0x01
facebook_username: kiyong.park.31
linkedin_username: 기용-박-b65932106
behance_username: hunter0x01
instagram_username: hunter0x01
medium_username: hunter0x01 
telegram_username: hunter0x01
dribbble_username: hunter0x01 
flickr_username: hunter0x01